2018-02-17 14:05:49,899 ERROR: Exception on /user/fred [GET] [in /home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seedub/pythonStuff/microblog/app/routes.py", line 76, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/seedub/pythonStuff/microblog/app/templates/user.html", line 14, in template
    {% elif no current_user.is_following(user) %}
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 164, in parse_statements
    self.stream.expect('block_end')
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'current_user'
2018-02-21 23:28:21,319 INFO: Microblog startup [in /home/seedub/pythonStuff/microblog/app/__init__.py:60]
2018-02-21 23:40:31,063 INFO: Microblog startup [in /home/seedub/pythonStuff/microblog/app/__init__.py:60]
2018-02-21 23:40:50,569 ERROR: Exception on /user/carlton [GET] [in /home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seedub/pythonStuff/microblog/app/routes.py", line 81, in user
    next_url = url_for('user', page=posts.next_num) if posts.has_next else None
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['page']. Did you forget to specify values ['username']?
2018-02-21 23:44:48,140 ERROR: Exception on /user/carlton [GET] [in /home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seedub/pythonStuff/microblog/app/routes.py", line 81, in user
    prev_url = url_for('user', username=user.username, page=posts.prev_num) if posts.has_prev else None
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/seedub/pythonStuff/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['page']. Did you forget to specify values ['username']?
